from app.schemas.sokqa import CoursePlan, PlanDocument, SokqaDocumentItem, SokqaDocumentPack
from app.config import get_settings
from app.services.gemini_client import GeminiClient
from app.services.generation_status import record_generation_source
from app.services.prompts import document_generation_prompt
from app.services.tts_text import normalize_tts_text


def generate_document_pack(plan: CoursePlan, document: PlanDocument, model: str | None = None) -> SokqaDocumentPack:
    if get_settings().gemini_provider == "gemini":
        try:
            settings = get_settings()
            content = GeminiClient().generate_json(
                document_generation_prompt(plan, document),
                model=model or settings.document_model,
            )
            content = normalize_document_content(content, plan, document)
            pack = SokqaDocumentPack.model_validate(content)
            record_generation_source("gemini", f"Document {document.id} generated by Gemini ({model or settings.document_model})")
            return pack
        except Exception as exc:
            record_generation_source("mock", f"Document {document.id} fell back to mock: {exc}")

    record_generation_source("mock", f"Document {document.id} generated by mock")
    return generate_mock_document_pack(plan, document)


def generate_mock_document_pack(plan: CoursePlan, document: PlanDocument) -> SokqaDocumentPack:
    items: list[SokqaDocumentItem] = []
    source_excerpt = (plan.sourceText or "").strip()
    for index in range(1, document.targetSectionCount + 1):
        point = document.keyPoints[(index - 1) % len(document.keyPoints)]
        if source_excerpt and plan.sourceMode == "document_only":
            text = f"{source_excerpt[:240]}。"
        elif source_excerpt and plan.sourceMode == "document_reference":
            text = (
                f"{source_excerpt[:180]}。"
                f"{point}について、{plan.targetUser}にも分かるように補足して整理します。"
                f"{plan.title}では、資料の趣旨を土台にして学習しやすい順序で理解します。"
            )
        else:
            text = (
                f"{document.title}のセクション{index}です。"
                f"{point}について、{plan.targetUser}にも分かるように短く確認します。"
                f"{plan.title}では、用語の意味と実際の使われ方を結びつけて覚えることが大切です。"
            )
        items.append(SokqaDocumentItem(id=f"doc-{index}", text=text))

    return SokqaDocumentPack(
        id=f"{plan.id}_{document.id}",
        title=document.title,
        description=document.goal,
        language=plan.language,
        author=plan.author,
        globalTags=[plan.id, plan.difficulty],
        documents=items,
    )


def normalize_document_content(content: dict, plan: CoursePlan, document: PlanDocument) -> dict:
    normalized = dict(content)
    normalized.setdefault("id", f"{plan.id}_{document.id}")
    normalized.setdefault("type", "document")
    normalized.setdefault("schemaVersion", 1)
    normalized.setdefault("title", document.title)
    normalized.setdefault("description", document.goal)
    normalized.setdefault("language", plan.language)
    normalized.setdefault("author", plan.author)
    normalized.setdefault("globalTags", [plan.id, plan.difficulty])

    documents = normalized.get("documents")
    if documents is None:
        documents = normalized.get("sections") or normalized.get("items") or []

    fixed_documents = []
    for index, item in enumerate(documents, start=1):
        if not isinstance(item, dict):
            item = {"text": str(item)}
        text = item.get("text") or item.get("body") or item.get("content")
        if not text:
            title = item.get("title", "")
            summary = item.get("summary") or item.get("description") or ""
            text = f"{title}。{summary}".strip("。")
        fixed = dict(item)
        fixed["id"] = f"doc-{index}"
        fixed["text"] = text
        fixed.pop("tts", None)
        fixed.pop("tags", None)
        fixed.pop("body", None)
        fixed.pop("content", None)
        fixed_documents.append(fixed)

    normalized["documents"] = fixed_documents
    return normalized
