import re
from datetime import date
from typing import Any

from app.config import get_settings
from app.schemas.common import ReadingPattern, normalize_tts_reading_mode, source_mode_for_material_mode
from app.schemas.request import PlanPackRequest, QuizPackSpec
from app.schemas.sokqa import CoursePlan, PlanDocument, PlanQuizPack
from app.services.gemini_client import GeminiClient
from app.services.document_generator import (
    STRICT_MAX_DOCUMENT_FILES,
    split_strict_source_sections,
    strict_source_limit_error,
    strict_source_paragraphs,
)
from app.services.llm_json import LlmJsonParseContext
from app.services.pack_metadata import resolve_creator_id
from app.services.source_material import normalize_source, source_prompt_block
from app.services.tagging import course_global_tags
from app.utils.ids import new_opaque_id, path_token, slugify


SCALE_CHAPTER_RANGES = {
    "quick": (3, 3),
    "standard": (6, 6),
    "large": (9, 9),
    "auto": (8, 12),
}

RANGE_TITLES = {
    2: ["前半の理解チェック", "後半の理解チェック"],
    3: ["前半の理解チェック", "中盤の理解チェック", "後半の理解チェック"],
    4: ["序盤の理解チェック", "前半の理解チェック", "後半の理解チェック", "終盤の理解チェック"],
}

RANGE_PURPOSES = ["key_concepts", "application", "application", "application"]
MAX_READING_PATTERN_COUNT = 8


FALLBACK_READING_PATTERNS = [
    ReadingPattern(
        id="alphabet_abbreviations",
        title="英略語はアルファベット読みで扱う",
        description="IT、AI、API、OS などの英略語は、必要に応じてカタカナのアルファベット読みとして扱う方針です。",
        examples=["IT -> アイティー", "API -> エーピーアイ", "OS -> オーエス"],
        recommended=True,
    ),
    ReadingPattern(
        id="dot_notation",
        title="ドット記法やファイル名を読み下す",
        description=".git、.env、.gitignore、app.config のようなドットや記号を含む表記を、読み上げで自然に聞こえるように扱う方針です。",
        examples=[".git -> ドット ギット", ".env -> ドット イーエヌブイ", ".gitignore -> ドット ギットイグノア"],
        recommended=True,
    ),
    ReadingPattern(
        id="technical_commands",
        title="コマンドや技術用語を読み下す",
        description="git checkout や npm install のようなコマンド・技術用語を、聞き取りやすい読みとして扱う方針です。",
        examples=["git checkout -> ギット チェックアウト", "npm install -> エヌピーエム インストール"],
        recommended=False,
    ),
    ReadingPattern(
        id="camel_case_terms",
        title="キャメルケースや区切り語を読みやすくする",
        description="localStorage や accessToken のような区切りのある技術語を、自然なまとまりで読めるように扱う方針です。",
        examples=["localStorage -> ローカルストレージ", "accessToken -> アクセストークン"],
        recommended=False,
    ),
    ReadingPattern(
        id="symbols_and_versions",
        title="記号・バージョン番号を聞き取りやすくする",
        description="スラッシュ、ハイフン、バージョン番号などを、聞き取りやすい読みとして扱う方針です。",
        examples=["v1.2 -> バージョン いち てん に", "A/B -> エー スラッシュ ビー"],
        recommended=False,
    ),
]


def _language_base(language: str | None) -> str:
    return (language or "ja").split("-")[0].lower()


def _is_ja(language: str | None) -> bool:
    return _language_base(language) == "ja"


def _localized_label(language: str | None, key: str) -> str:
    labels = {
        "ja": {
            "learning_pack": "学習パック",
            "generated_on": "生成日",
            "comprehension_check": "理解チェック",
            "integrated_review": "総合確認",
            "full_range": "全範囲",
            "chapter": "章",
            "chapters": "章",
        },
        "en": {
            "learning_pack": "Learning Pack",
            "generated_on": "Generated on",
            "comprehension_check": "Comprehension Check",
            "integrated_review": "Integrated Review",
            "full_range": "Full Range",
            "chapter": "Chapter",
            "chapters": "Chapters",
        },
        "ko": {
            "learning_pack": "학습 팩",
            "generated_on": "생성일",
            "comprehension_check": "이해 확인",
            "integrated_review": "종합 복습",
            "full_range": "전체 범위",
            "chapter": "장",
            "chapters": "장",
        },
        "zh": {
            "learning_pack": "学习包",
            "generated_on": "生成日期",
            "comprehension_check": "理解检查",
            "integrated_review": "综合复习",
            "full_range": "全部范围",
            "chapter": "章",
            "chapters": "章",
        },
        "es": {
            "learning_pack": "paquete de aprendizaje",
            "generated_on": "Generado el",
            "comprehension_check": "Comprobacion de comprension",
            "integrated_review": "Repaso integral",
            "full_range": "rango completo",
            "chapter": "capitulo",
            "chapters": "capitulos",
        },
    }
    base = _language_base(language)
    return labels.get(base, labels["en"])[key]


def _ai_disclaimer(language: str | None) -> str:
    disclaimers = {
        "ja": "この内容はAIが生成したものです。重要な判断の前にご自身で事実確認をしてください。",
        "en": "This content was generated by AI. Please verify facts yourself before making important decisions.",
        "ko": "이 콘텐츠는 AI가 생성했습니다. 중요한 판단 전에 직접 사실을 확인해 주세요.",
        "zh": "本内容由 AI 生成。做出重要判断前，请自行核实事实。",
        "es": "Este contenido fue generado por IA. Verifica los datos antes de tomar decisiones importantes.",
    }
    return disclaimers.get(_language_base(language), disclaimers["en"])


def _document_count(request: PlanPackRequest) -> int:
    if request.generationUnit == "quiz":
        return 0
    if request.docCount is not None:
        return request.docCount
    if request.documentCount:
        return request.documentCount
    if request.generationUnit == "document":
        return 1
    if request.scale == "quick":
        return 3
    if request.scale == "standard":
        return 6
    if request.scale == "large":
        return 9
    return 10


def _exact_document_count(request: PlanPackRequest) -> int | None:
    if request.generationUnit == "quiz":
        return 0
    if request.docCount is not None:
        return request.docCount
    if request.documentCount:
        return request.documentCount
    if request.generationUnit == "document":
        return 1
    if request.scale == "quick":
        return 3
    if request.scale == "standard":
        return 6
    if request.scale == "large":
        return 9
    return None


def _question_count(request: PlanPackRequest) -> int:
    return request.questionCount or 30


def _quiz_pack_count(request: PlanPackRequest, document_count: int) -> int:
    if request.generationUnit == "document":
        return 0
    if request.quizCount is not None:
        return request.quizCount
    if request.quizPacks:
        return len(request.quizPacks)
    if request.generationUnit == "quiz":
        return 1
    if request.scale == "quick":
        return 1
    if request.scale == "standard":
        return 2
    if request.scale == "large":
        return 3
    if document_count <= 8:
        return 3
    if document_count <= 10:
        return 4
    return 5


def _range_quiz_pack_count(scale: str, document_count: int) -> int:
    if scale in {"quick", "standard"}:
        return 2
    if document_count <= 6:
        return 2
    if document_count <= 10:
        return 3
    return 4


def _split_document_ids(document_ids: list[str], chunk_count: int) -> list[list[str]]:
    if chunk_count <= 0:
        return []
    base_size, remainder = divmod(len(document_ids), chunk_count)
    chunks = []
    start = 0
    for index in range(chunk_count):
        size = base_size + (1 if index < remainder else 0)
        end = start + size
        chunks.append(document_ids[start:end])
        start = end
    return chunks


def _section_count(request: PlanPackRequest) -> int:
    if request.sectionsPerDocument:
        return request.sectionsPerDocument
    return 42


def _requested_document_count(request: PlanPackRequest) -> str:
    if request.generationUnit == "quiz":
        return "0 chapters. The user requested quiz-only generation."
    if request.docCount is not None:
        return (
            f"{request.docCount} chapters exactly. "
            "You must return exactly this many documents."
        )
    if request.documentCount:
        return (
            f"{request.documentCount} chapters exactly. "
            "You must return exactly this many documents."
        )
    if request.scale == "auto":
        return (
            "Not specified. Scale is auto: return 8-12 chapters. "
            "Let the source complexity, theme, target user, and difficulty decide the exact count."
        )
    min_count, max_count = SCALE_CHAPTER_RANGES[request.scale]
    return (
        f"Not specified. Scale is {request.scale}: return {min_count}-{max_count} chapters. "
        "Within that range, optimize the chapter count for the theme, target user, and difficulty."
    )


def _requested_section_count(request: PlanPackRequest) -> str:
    if request.sectionsPerDocument:
        return (
            f"{request.sectionsPerDocument} sections per document exactly. "
            "Every document.targetSectionCount must use this number."
        )
    return (
        "Not specified. Propose a suitable targetSectionCount from 35 to 50 for each chapter, with 42 as the default target. "
        "Optimize within this range per chapter; do not vary section count by scale."
    )


def _fallback_short_title(request: PlanPackRequest) -> str:
    text = re.sub(r"\s+", "", request.theme).strip()
    text = re.sub(r"(学習パック|講座|コース)$", "", text)
    if not text:
        return "Sokqa"
    if len(text) > 16:
        return text[:16]
    return text


def _description_from_request(request: PlanPackRequest, fallback: str) -> str:
    description = fallback
    if request.descriptionMode == "manual" and request.manualDescription:
        description = request.manualDescription.strip()
    extras: list[str] = []
    if request.descriptionIncludeDate:
        label = _localized_label(request.language, "generated_on")
        extras.append(f"{label}: {date.today().isoformat()}")
    if request.descriptionIncludeAiDisclaimer:
        extras.append(_ai_disclaimer(request.language))
    if extras:
        description = f"{description}\n" + "\n".join(extras)
    return description


def _fallback_pack_title(request: PlanPackRequest) -> str:
    return f"{request.theme} {_localized_label(request.language, 'learning_pack')}"


def _fallback_pack_description(request: PlanPackRequest) -> str:
    if _is_ja(request.language):
        return f"{request.targetUser}向けの{request.theme}用Sokqa学習パックです。"
    return f"A Sokqa learning pack about {request.theme} for {request.targetUser}."


def _fallback_document_title(request: PlanPackRequest, index: int) -> str:
    return f"{request.theme}の重要領域 {index}" if _is_ja(request.language) else f"Key Area {index} of {request.theme}"


def _fallback_document_goal(request: PlanPackRequest, index: int) -> str:
    if _is_ja(request.language):
        return f"{request.targetUser}が{request.theme}の領域{index}で扱う基本事項と実践上の注意点を理解する"
    return f"{request.targetUser} will understand the fundamentals and practical cautions in area {index} of {request.theme}."


def _fallback_document_key_points(request: PlanPackRequest, index: int) -> list[str]:
    if _is_ja(request.language):
        return [
            f"{request.theme}の領域{index}で最初に押さえる用語",
            f"領域{index}で起こりやすい誤解",
            f"{request.targetUser}が実務や学習で使う場面",
        ]
    return [
        f"Core terms to learn first in area {index} of {request.theme}",
        f"Common misunderstandings in area {index}",
        f"How {request.targetUser} can use this in practice or study",
    ]


def _global_tags_from_request(request: PlanPackRequest, plan: CoursePlan) -> list[str]:
    if request.globalTagsMode == "manual" and request.manualGlobalTags:
        return request.manualGlobalTags[:3]
    return course_global_tags(plan)


def _effective_request_tts_mode(request: PlanPackRequest) -> str:
    if not request.includeTts or not request.enableTtsOptimize:
        return "none"
    return normalize_tts_reading_mode(request.ttsReadingMode) or get_settings().tts_reading_mode


def _planner_prompt(request: PlanPackRequest) -> str:
    source_block = source_prompt_block(request.sourceText, request.sourceMode)
    source_section = f"\n\n{source_block}" if source_block else ""
    tts_mode = _effective_request_tts_mode(request)
    reading_pattern_rules = (
        """
- Also propose optional reading-pattern policies that may help TTS generation for this theme.
- proposedReadingPatterns are selectable policies, not fixed word dictionaries. Do not mix them with ttsRules.
- Each reading pattern should describe a general reading strategy, include 1 to 3 examples, and use a stable snake_case id.
- Examples must be real transformations in "source -> reading" format: source and reading must not be identical, source and reading must not be empty, and do not append stray suffixes or unrelated characters.
- Do not use already-natural katakana words as examples unless the source contains symbols, ASCII, kanji, or other notation that actually changes in the reading.
- Consider these common categories and propose the ones that are relevant to the theme:
  - dot notation and symbol-heavy file/config names, e.g. ".git -> ドットギット", ".env -> ドットイーエヌブイ", ".gitignore -> ドットギットイグノア".
  - alphabet reading for abbreviations, e.g. "OS -> オーエス", "API -> エーピーアイ", "URL -> ユーアールエル".
  - commands and technical phrases, e.g. "git checkout -> ギット チェックアウト".
  - camelCase or delimiter-separated terms, e.g. "localStorage -> ローカルストレージ".
- Prioritize categories that match the theme/source text. Do not force unrelated patterns just to fill the list.
- Set recommended=true only when the notation is likely to appear in this theme, target user, source text, document titles, or key points. Set dot notation and command patterns to recommended=false unless dot files, commands, file names, or similar notation actually appear.
- Examples must use the concrete "source -> reading" format so users can judge the pattern quickly.
""".rstrip()
        if tts_mode == "llm"
        else """
- Do not propose reading-pattern policies because the selected TTS mode will not use them.
- Return proposedReadingPatterns as an empty array.
""".rstrip()
    )
    additional_conditions = request.customInstructions or "none"
    return f"""
Return strict JSON only. Do not use markdown fences.
出力は必ずJSONのみ。Markdown、説明文、コードブロックは禁止。JSON内の文字列は必ずエスケープする。

Design a Sokqa CoursePlan outline for a learning pack.
The user will review and edit this outline before generation, so focus on a concrete, useful chapter plan.

Input:
- theme: {request.theme}
- targetUser: {request.targetUser}
- difficulty: {request.difficulty}
- scale: {request.scale}
- language: {request.language}
- structurePolicy: {request.structurePolicy}
- generationUnit: {request.generationUnit}
- requested quizCount: {request.quizCount if request.quizCount is not None else "planner/default"}
- requested questionCount: {request.questionCount if request.questionCount is not None else "30 per quiz"}
- materialMode: {request.materialMode}
- requested documentCount: {_requested_document_count(request)}
- requested sectionsPerDocument: {_requested_section_count(request)}

# 生成ルール
以下は必ず守る制約です。出力本文には含めないでください。
additional conditions: {additional_conditions}
{additional_conditions}
{source_section}

Rules:
- The documents array is the most important output.
- Write title, shortTitle, description, document titles/goals/keyPoints, quiz-related labels, and automatic metadata in the pack language ({request.language}) unless the user explicitly supplied those fields in another language.
- Respect the user's additional conditions when they are provided, while still following the schema, safety, material mode, and generation-unit constraints.
- structurePolicy standard: use the existing balanced course structure.
- structurePolicy listening: write the outline as connected narrative beats for listening-first content. Do not design glossary entries or term-by-term definition lists. Prefer fewer sections that flow from context to explanation to examples, with short natural sentences and minimal symbol-heavy or bullet-list-dependent structure.
- materialMode reference: reference material may be supplemented when needed.
- materialMode source_only: use only the supplied material, but you may organize and rewrite it as learning content.
- materialMode strict: plan for source-only document generation. The final document text will be copied mechanically from the material without LLM rewriting. Do not add facts, terms, examples, claims, or inferred details that are absent from the material.
- Also return shortTitle: a short pack identifier used as a title prefix, such as "Git入門". Keep it concise.
- Chapter titles must describe the actual topic content. Do not return generic titles such as "第1章" or "{request.theme} 第1章".
- The document order must be a natural learning path from basics to application/review.
- Each document must have a unique, theme-specific title.
- Each document.goal must describe what the learner will understand in that specific chapter.
- Each document.keyPoints must be specific to that chapter. Do not reuse the same keyPoints across chapters.
- If documentCount was specified, return exactly that many documents.
- If documentCount was not specified and scale is quick, return 3-5 documents.
- If documentCount was not specified and scale is quick, return exactly 3 documents.
- If documentCount was not specified and scale is standard, return exactly 6 documents.
- If documentCount was not specified and scale is large, return exactly 9 documents.
- If documentCount was not specified and scale is auto, return 8-12 documents.
- If sectionsPerDocument was specified, every targetSectionCount must exactly match it.
- keyPoints should contain 3 to 6 concise items. For structurePolicy listening, keyPoints must be narrative beats in the order the spoken explanation should flow, not isolated term labels.
- If sectionsPerDocument was not specified, targetSectionCount must be an integer from 35 to 50 for every document. Prefer 42 unless the source structure clearly calls for a different count.
- targetSectionCount must be an integer from 1 to 50.
{reading_pattern_rules}

Return this JSON shape:
{{
  "title": "pack title",
  "shortTitle": "short pack identifier",
  "description": "short description, including why this chapter count fits if documentCount was not specified",
  "proposedReadingPatterns": [
    {{
      "id": "alphabet_abbreviations",
      "title": "short pattern title",
      "description": "what to do when generating learner text",
      "examples": ["IT -> アイティー"],
      "recommended": true
    }}
  ],
  "documents": [
    {{
      "title": "specific chapter title",
      "goal": "chapter-specific learning goal",
      "keyPoints": ["specific point 1", "specific point 2", "specific point 3"],
      "targetSectionCount": 40
    }}
  ]
}}
""".strip()


def _build_quiz_packs(request: PlanPackRequest, document_ids: list[str]) -> list[PlanQuizPack]:
    requested_count = _quiz_pack_count(request, len(document_ids))
    if requested_count <= 0:
        return []
    if request.quizPacks:
        return [
            PlanQuizPack(
                id=slugify(spec.id, "quiz"),
                title=spec.title,
                purpose=spec.purpose if spec.purpose in {"key_concepts", "application", "integrated_review"} else "custom",
                questionCount=spec.questionCount,
                difficulty=spec.difficulty,
                sourceDocumentIds=document_ids,
            )
            for spec in request.quizPacks[:requested_count]
        ]

    if requested_count == 1:
        return [
            PlanQuizPack(
                id="quiz_single_01",
                title=_localized_label(request.language, "comprehension_check"),
                purpose="key_concepts",
                questionCount=_question_count(request),
                difficulty=request.difficulty,
                sourceDocumentIds=document_ids,
            )
        ]

    include_integrated = requested_count >= 3
    range_count = max(1, requested_count - 1) if include_integrated else requested_count
    chunks = _split_document_ids(document_ids, range_count)
    question_count = _question_count(request)
    range_titles = RANGE_TITLES.get(range_count) if _is_ja(request.language) else None
    quiz_packs = [
        PlanQuizPack(
            id=f"quiz_range_{index + 1:02d}",
            title=(
                range_titles
                or [
                    f"{_localized_label(request.language, 'comprehension_check')} {item + 1}"
                    for item in range(range_count)
                ]
            )[index],
            purpose=RANGE_PURPOSES[index] if index < len(RANGE_PURPOSES) else "application",
            questionCount=question_count,
            difficulty=request.difficulty,
            sourceDocumentIds=chunk,
        )
        for index, chunk in enumerate(chunks)
    ]
    if include_integrated and len(quiz_packs) < requested_count:
        quiz_packs.append(
            PlanQuizPack(
                id="quiz_integrated_review",
                title="総合・応用クイズ",
                purpose="integrated_review",
                questionCount=question_count,
                difficulty=request.difficulty,
                sourceDocumentIds=document_ids,
            )
        )
    return quiz_packs


def _fallback_documents(request: PlanPackRequest) -> list[PlanDocument]:
    count = _document_count(request)
    section_count = _section_count(request)
    documents = []
    for index in range(1, count + 1):
        doc_id = f"doc_{index:02d}"
        documents.append(
            PlanDocument(
                id=doc_id,
                title=_fallback_document_title(request, index),
                goal=_fallback_document_goal(request, index),
                keyPoints=_fallback_document_key_points(request, index),
                targetSectionCount=section_count,
            )
        )
    return documents


def _normalize_key_points(value: Any, theme: str, index: int) -> list[str]:
    if not isinstance(value, list):
        return [
            f"{theme}の基本事項",
            "重要用語",
            "実践での使い方",
        ]
    points = [str(item).strip() for item in value if str(item).strip()]
    if len(points) < 3:
        points.extend([f"{theme}の重要ポイント{index}", "関連用語", "確認すべき注意点"])
    return points[:6]


def _sanitize_section_count(value: Any, request: PlanPackRequest) -> int:
    if request.sectionsPerDocument:
        return request.sectionsPerDocument
    try:
        count = int(value)
    except (TypeError, ValueError):
        count = _section_count(request)
    return max(35, min(50, count))


def _documents_from_planner_response(data: dict[str, Any], request: PlanPackRequest) -> list[PlanDocument]:
    raw_documents = data.get("documents")
    if not isinstance(raw_documents, list):
        return []

    exact_count = _exact_document_count(request)
    if exact_count == 0:
        return []
    if exact_count is not None:
        raw_documents = raw_documents[:exact_count]
    elif request.scale == "auto":
        raw_documents = raw_documents[:12]

    documents = []
    for index, raw in enumerate(raw_documents, start=1):
        if not isinstance(raw, dict):
            continue
        title = str(raw.get("title") or "").strip()
        goal = str(raw.get("goal") or "").strip()
        if not title or not goal:
            continue
        documents.append(
            PlanDocument(
                id=f"doc_{index:02d}",
                title=title,
                goal=goal,
                keyPoints=_normalize_key_points(raw.get("keyPoints"), request.theme, index),
                targetSectionCount=_sanitize_section_count(raw.get("targetSectionCount"), request),
            )
        )
    return documents


def _short_title_from_planner_response(data: dict[str, Any], request: PlanPackRequest) -> str:
    short_title = str(data.get("shortTitle") or "").strip()
    if not short_title:
        return _fallback_short_title(request)
    short_title = re.sub(r"\s+", "", short_title)
    return short_title[:16] or _fallback_short_title(request)


def _strip_document_title_prefix(title: str, short_title: str) -> str:
    pattern = rf"^{re.escape(short_title)}\s+\d+\.\s*"
    return re.sub(pattern, "", title).strip()


def _prefix_document_titles(documents: list[PlanDocument], short_title: str) -> list[PlanDocument]:
    titled_documents: list[PlanDocument] = []
    for index, document in enumerate(documents, start=1):
        base_title = _strip_document_title_prefix(document.title, short_title)
        titled_documents.append(document.model_copy(update={"title": f"{short_title} {index}. {base_title}"}))
    return titled_documents


def _strict_source_documents(request: PlanPackRequest, source_text: str) -> list[PlanDocument]:
    paragraphs = strict_source_paragraphs(source_text) or [source_text.strip()]
    chunks = split_strict_source_sections(paragraphs)
    return [
        PlanDocument(
            id=f"doc_{index:02d}",
            title=f"資料ファイル {index}" if _is_ja(request.language) else f"Source File {index}",
            goal=(
                f"元資料の段落{start + 1}〜{end}を改変せずに格納する"
                if _is_ja(request.language)
                else f"Store source paragraphs {start + 1}-{end} without rewriting."
            ),
            keyPoints=[],
            targetSectionCount=len(chunk),
        )
        for index, (chunk, start, end) in enumerate(_chunks_with_offsets(chunks), start=1)
    ]


def _chunks_with_offsets(chunks: list[list[str]]) -> list[tuple[list[str], int, int]]:
    offset = 0
    indexed = []
    for chunk in chunks:
        start = offset
        offset += len(chunk)
        indexed.append((chunk, start, offset))
    return indexed


def _document_index(document_id: str, document_ids: list[str]) -> int | None:
    try:
        return document_ids.index(document_id) + 1
    except ValueError:
        match = re.search(r"(\d+)$", document_id)
        return int(match.group(1)) if match else None


def _chapter_range_label(indexes: list[int], total_count: int, language: str | None = None) -> str:
    if not _is_ja(language):
        chapter = _localized_label(language, "chapter")
        chapters = _localized_label(language, "chapters")
        if not indexes:
            return f"{chapters} 1-{total_count}" if total_count > 1 else f"{chapter} 1"
        start, end = min(indexes), max(indexes)
        return f"{chapter} {start}" if start == end else f"{chapters} {start}-{end}"
    if not indexes:
        return f"1〜{total_count}章" if total_count > 1 else "1章"
    start, end = min(indexes), max(indexes)
    return f"{start}章" if start == end else f"{start}〜{end}章"


def _topic_words_for_documents(documents: list[PlanDocument], indexes: list[int], *, max_words: int = 2) -> str:
    words: list[str] = []
    for index in indexes:
        if index < 1 or index > len(documents):
            continue
        document = documents[index - 1]
        source = re.sub(r"^.+?\s+\d+\.\s*", "", document.title).strip()
        parts = re.split(r"[、,・／/と&＆:：\s]+", source)
        for part in parts:
            word = part.strip("（）()「」『』")
            if word and word not in words:
                words.append(word)
            if len(words) >= max_words:
                return "・".join(words)
    return ""


def _title_quiz_packs(quiz_packs: list[PlanQuizPack], documents: list[PlanDocument], short_title: str, language: str | None = None) -> list[PlanQuizPack]:
    document_ids = [document.id for document in documents]
    total_count = len(documents)
    titled_quizzes: list[PlanQuizPack] = []
    range_index = 1
    for quiz_pack in quiz_packs:
        indexes = [
            index
            for document_id in quiz_pack.sourceDocumentIds
            if (index := _document_index(document_id, document_ids)) is not None
        ]
        if quiz_pack.purpose == "integrated_review" or (total_count > 0 and set(quiz_pack.sourceDocumentIds) == set(document_ids)):
            chapter_range = _chapter_range_label(list(range(1, total_count + 1)), total_count, language)
            if _is_ja(language):
                title = f"{short_title} 総合確認（{chapter_range}: 全範囲）"
            else:
                title = (
                    f"{short_title} {_localized_label(language, 'integrated_review')} "
                    f"({chapter_range}: {_localized_label(language, 'full_range')})"
                )
        else:
            chapter_range = _chapter_range_label(indexes, total_count, language)
            topic = _topic_words_for_documents(documents, indexes)
            if _is_ja(language):
                suffix = f": {topic}" if topic else ""
                title = f"{short_title} 理解チェック{range_index}（{chapter_range}{suffix}）"
            else:
                suffix = f": {topic}" if topic else ""
                title = f"{short_title} {_localized_label(language, 'comprehension_check')} {range_index} ({chapter_range}{suffix})"
            range_index += 1
        titled_quizzes.append(quiz_pack.model_copy(update={"title": title}))
    return titled_quizzes


def _fallback_reading_patterns(request: PlanPackRequest) -> list[ReadingPattern]:
    patterns = [pattern.model_copy(deep=True) for pattern in FALLBACK_READING_PATTERNS]
    theme_text = f"{request.theme} {request.sourceText or ''}".lower()
    if not any(token in theme_text for token in ["git", "api", "it", "ai", "os", "."]):
        return patterns[:1]
    return patterns


def _reading_pattern_signature(pattern: ReadingPattern) -> str:
    text = " ".join([pattern.id, pattern.title, pattern.description, *pattern.examples]).lower()
    if any(token in text for token in [".git", ".env", ".gitignore", "dot notation", "ドット記法", "ドットファイル"]):
        return "dot_notation"
    if any(token in text for token in ["api", "url", "os", "英略語", "アルファベット"]):
        return "alphabet_abbreviations"
    if any(token in text for token in ["checkout", "install", "command", "コマンド"]):
        return "technical_commands"
    if any(token in text for token in ["camel", "localstorage", "キャメル"]):
        return "camel_case_terms"
    if any(token in text for token in ["version", "slash", "バージョン", "スラッシュ"]):
        return "symbols_and_versions"
    return re.sub(r"\s+", "", pattern.title).lower() or pattern.id


def _reading_pattern_context(request: PlanPackRequest, documents: list[PlanDocument] | None = None) -> str:
    document_text = ""
    if documents:
        document_text = " ".join(
            " ".join([document.title, document.goal, *document.keyPoints])
            for document in documents
        )
    return " ".join([request.theme, request.targetUser, request.sourceText or "", document_text]).lower()


def _recommended_allowed_for_pattern(pattern: ReadingPattern, request: PlanPackRequest, documents: list[PlanDocument] | None = None) -> bool:
    signature = _reading_pattern_signature(pattern)
    context = _reading_pattern_context(request, documents)
    if signature == "dot_notation":
        return bool(re.search(r"(^|\s|\W)\.[a-z0-9_-]+", context)) or any(token in context for token in ["dotfile", "dot file", "ドットファイル", "ドット記法"])
    if signature == "technical_commands":
        return any(token in context for token in ["git ", "npm ", "pip ", "docker ", "checkout", "install", "commit", "コマンド", "cli"])
    if signature == "camel_case_terms":
        return bool(re.search(r"[a-z]+[A-Z][A-Za-z0-9]*", _reading_pattern_context(request, documents)))
    if signature == "symbols_and_versions":
        return bool(re.search(r"\bv?\d+\.\d+|[A-Za-z0-9]+/[A-Za-z0-9]+|バージョン|スラッシュ", context))
    return True


def _merge_reading_patterns(
    proposed: list[ReadingPattern],
    fallback: list[ReadingPattern],
    request: PlanPackRequest | None = None,
    documents: list[PlanDocument] | None = None,
    *,
    max_count: int = MAX_READING_PATTERN_COUNT,
) -> list[ReadingPattern]:
    merged: list[ReadingPattern] = []
    seen_ids: set[str] = set()
    seen_titles: set[str] = set()
    seen_signatures: set[str] = set()
    for pattern in [*fallback, *proposed]:
        title_key = re.sub(r"\s+", "", pattern.title).lower()
        signature = _reading_pattern_signature(pattern)
        if pattern.id in seen_ids or title_key in seen_titles or signature in seen_signatures:
            continue
        if request is not None and pattern.recommended and not _recommended_allowed_for_pattern(pattern, request, documents):
            pattern = pattern.model_copy(update={"recommended": False})
        merged.append(pattern)
        seen_ids.add(pattern.id)
        seen_titles.add(title_key)
        seen_signatures.add(signature)
    return merged[:max_count]


def _apply_recommended_guard(
    patterns: list[ReadingPattern],
    request: PlanPackRequest,
    documents: list[PlanDocument] | None = None,
) -> list[ReadingPattern]:
    guarded: list[ReadingPattern] = []
    for pattern in patterns:
        if pattern.recommended and not _recommended_allowed_for_pattern(pattern, request, documents):
            pattern = pattern.model_copy(update={"recommended": False})
        guarded.append(pattern)
    return guarded


def _normalize_reading_example_part(value: str) -> str:
    return re.sub(r"\s+", "", value).strip().lower()


def _source_needs_reading_example(source: str) -> bool:
    compact = re.sub(r"\s+", "", source)
    if not compact:
        return False
    return bool(re.search(r"[A-Za-z0-9一-龯々〆ヵヶ\.／/\\_\-]", compact))


def _valid_reading_examples(raw_examples: Any, *, max_examples: int = 3) -> list[str]:
    if not isinstance(raw_examples, list):
        return []
    valid_examples: list[str] = []
    for raw_example in raw_examples:
        example = str(raw_example).strip()
        if "->" not in example:
            continue
        source, reading = [part.strip() for part in example.split("->", 1)]
        if not source or not reading:
            continue
        if _normalize_reading_example_part(source) == _normalize_reading_example_part(reading):
            continue
        if not _source_needs_reading_example(source):
            continue
        valid_examples.append(f"{source} -> {reading}")
        if len(valid_examples) >= max_examples:
            break
    return valid_examples


def _reading_patterns_from_planner_response(data: dict[str, Any], request: PlanPackRequest) -> list[ReadingPattern]:
    raw_patterns = data.get("proposedReadingPatterns")
    fallback_patterns = _fallback_reading_patterns(request)
    if not isinstance(raw_patterns, list):
        return fallback_patterns[:MAX_READING_PATTERN_COUNT]

    patterns: list[ReadingPattern] = []
    seen_ids: set[str] = set()
    for index, raw in enumerate(raw_patterns, start=1):
        if not isinstance(raw, dict):
            continue
        title = str(raw.get("title") or "").strip()
        description = str(raw.get("description") or "").strip()
        if not title or not description:
            continue
        pattern_id = slugify(str(raw.get("id") or title), f"reading_pattern_{index}")
        if pattern_id in seen_ids:
            pattern_id = f"{pattern_id}_{index}"
        seen_ids.add(pattern_id)
        examples = _valid_reading_examples(raw.get("examples"))
        patterns.append(
            ReadingPattern(
                id=pattern_id,
                title=title,
                description=description,
                examples=examples,
                recommended=bool(raw.get("recommended", False)) if examples else False,
            )
        )
    return _merge_reading_patterns(patterns, fallback_patterns, request)


def _key_points_signature(document: PlanDocument) -> tuple[str, ...]:
    return tuple(point.strip().lower() for point in document.keyPoints)


def _is_generic_title(title: str, theme: str) -> bool:
    compact = re.sub(r"\s+", "", title)
    theme_compact = re.sub(r"\s+", "", theme)
    generic_patterns = [
        r"^第\d+章$",
        r"^第[一二三四五六七八九十]+章$",
        rf"^{re.escape(theme_compact)}第\d+章$",
        rf"^{re.escape(theme_compact)}第[一二三四五六七八九十]+章$",
    ]
    return any(re.match(pattern, compact) for pattern in generic_patterns)


def _validate_planned_documents(documents: list[PlanDocument], request: PlanPackRequest) -> list[str]:
    errors = []
    if request.generationUnit != "quiz" and not documents:
        errors.append("documents must not be empty")
    exact_count = _exact_document_count(request)
    if exact_count is not None and len(documents) != exact_count:
        errors.append(f"documents must contain exactly {exact_count} items")
    if request.generationUnit != "quiz" and exact_count is None and request.scale in SCALE_CHAPTER_RANGES and documents:
        min_count, max_count = SCALE_CHAPTER_RANGES[request.scale]
        if not min_count <= len(documents) <= max_count:
            errors.append(f"documents must contain {min_count}-{max_count} items for {request.scale} scale")
    if documents:
        signatures = {_key_points_signature(document) for document in documents}
        if len(documents) > 1 and len(signatures) == 1:
            errors.append("keyPoints must not be identical across all documents")
        for document in documents:
            if _is_generic_title(document.title, request.theme):
                errors.append(f"document title is too generic: {document.title}")
    return errors


def _gemini_plan_parts(
    request: PlanPackRequest, model: str | None
) -> tuple[str | None, str | None, str, list[PlanDocument], list[ReadingPattern]]:
    data = GeminiClient().generate_json(
        _planner_prompt(request),
        model=model,
        parse_context=LlmJsonParseContext(
            generation_unit="plan",
            model=model or get_settings().planner_model,
            theme=request.theme,
            title=request.theme,
            source_text=request.sourceText,
            additional_instructions=request.customInstructions,
            tts_reading_mode=_effective_request_tts_mode(request),
            language=request.language,
            difficulty=request.difficulty,
            scale=request.scale,
        ),
    )
    title = str(data.get("title") or "").strip() or None
    short_title = _short_title_from_planner_response(data, request)
    description = str(data.get("description") or "").strip() or None
    documents = _documents_from_planner_response(data, request)
    reading_patterns = _reading_patterns_from_planner_response(data, request)
    reading_patterns = _apply_recommended_guard(reading_patterns, request, documents)
    errors = _validate_planned_documents(documents, request)
    if errors:
        raise ValueError("; ".join(errors))
    return title, description, short_title, documents, reading_patterns


def create_course_plan(request: PlanPackRequest, model: str | None = None) -> CoursePlan:
    if request.materialMode == "strict" and request.generationUnit != "document":
        request = request.model_copy(update={"materialMode": "source_only"})
    settings = get_settings()
    pack_id = slugify(request.theme, "sokqa_pack")
    slug = path_token(request.slug or slugify(request.theme, "sokqa-pack").replace("_", "-"), pack_id)
    title = _fallback_pack_title(request)
    description = _description_from_request(request, _fallback_pack_description(request))
    source_text, source_mode = normalize_source(request.sourceText, request.sourceMode)
    source_mode = source_mode_for_material_mode(request.materialMode, source_mode) if source_text else None
    short_title = _fallback_short_title(request)
    tts_mode = _effective_request_tts_mode(request)

    if settings.gemini_provider == "gemini":
        try:
            planned_title, planned_description, short_title, documents, reading_patterns = _gemini_plan_parts(request, model)
            title = planned_title or title
            if request.descriptionMode != "manual":
                description = _description_from_request(request, planned_description or description)
        except Exception:
            documents = _fallback_documents(request)
            reading_patterns = _apply_recommended_guard(_fallback_reading_patterns(request), request, documents)
    else:
        documents = _fallback_documents(request)
        reading_patterns = _apply_recommended_guard(_fallback_reading_patterns(request), request, documents)

    validation_errors = _validate_planned_documents(documents, request)
    if validation_errors:
        raise ValueError("; ".join(validation_errors))

    tts_rules = request.userTtsRules if request.includeTts else []
    if tts_mode != "llm":
        reading_patterns = []
    strict_section_count = None
    strict_file_count = None
    strict_limit_exceeded = False
    if request.materialMode == "strict" and source_text:
        documents = _strict_source_documents(request, source_text)
        strict_section_count = sum(document.targetSectionCount for document in documents)
        strict_file_count = len(documents)
        strict_limit_exceeded = strict_source_limit_error(strict_file_count) is not None
    documents = _prefix_document_titles(documents, short_title)
    quiz_packs = _title_quiz_packs(_build_quiz_packs(request, [document.id for document in documents]), documents, short_title, request.language)

    plan = CoursePlan(
        id=pack_id,
        creatorId=resolve_creator_id(request.creatorId),
        creatorDisplayName=request.creatorDisplayName,
        contentId=path_token(request.contentId or new_opaque_id("cnt"), "cnt_default"),
        slug=slug,
        shortTitle=short_title,
        title=title,
        description=description,
        language=request.language,
        customInstructions=request.customInstructions,
        targetUser=request.targetUser,
        difficulty=request.difficulty,
        scale=request.scale,
        structurePolicy=request.structurePolicy,
        generationUnit=request.generationUnit,
        docCount=request.docCount,
        quizCount=request.quizCount,
        materialMode=request.materialMode,
        questionCount=request.questionCount,
        sectionsPerDocument=request.sectionsPerDocument,
        globalTagsMode=request.globalTagsMode,
        manualGlobalTags=request.manualGlobalTags,
        descriptionMode=request.descriptionMode,
        manualDescription=request.manualDescription,
        descriptionIncludeDate=request.descriptionIncludeDate,
        descriptionIncludeAiDisclaimer=request.descriptionIncludeAiDisclaimer,
        answerPositionMode=request.answerPositionMode,
        author=settings.sokqa_author,
        enableTtsOptimize=request.includeTts and request.enableTtsOptimize,
        ttsReadingMode=tts_mode,
        ttsLanguageSettings=request.ttsLanguageSettings if tts_mode == "multilingual" else None,
        model=request.model,
        docModel=request.docModel,
        quizModel=request.quizModel,
        plannerModel=request.plannerModel,
        sourceText=source_text,
        sourceMode=source_mode,
        strictSourceSectionCount=strict_section_count,
        strictSourceFileCount=strict_file_count,
        strictSourceMaxFiles=STRICT_MAX_DOCUMENT_FILES if strict_file_count is not None else None,
        strictSourceLimitExceeded=strict_limit_exceeded,
        documents=documents,
        quizPacks=quiz_packs,
        ttsRules=tts_rules,
        proposedReadingPatterns=reading_patterns,
    )
    return plan.model_copy(update={"globalTags": _global_tags_from_request(request, plan)})
