from app.schemas.sokqa import CoursePlan, PlanQuizPack, SokqaDocumentPack, SokqaQuestion, SokqaQuizPack
from app.config import get_settings
from app.services.gemini_client import GeminiClient
from app.services.generation_status import record_generation_source
from app.services.prompts import quiz_generation_prompt


def _source_snippets(document_packs: list[SokqaDocumentPack]) -> list[str]:
    snippets: list[str] = []
    for pack in document_packs:
        for item in pack.documents:
            snippets.append(item.text)
    return snippets or ["学習内容を確認します。"]


def generate_quiz_pack(
    plan: CoursePlan,
    quiz_plan: PlanQuizPack,
    document_packs: list[SokqaDocumentPack],
    model: str | None = None,
) -> SokqaQuizPack:
    if get_settings().gemini_provider == "gemini":
        try:
            settings = get_settings()
            content = GeminiClient().generate_json(
                quiz_generation_prompt(plan, quiz_plan, document_packs),
                model=model or settings.quiz_model,
            )
            content = normalize_quiz_content(content, plan, quiz_plan)
            pack = SokqaQuizPack.model_validate(content)
            record_generation_source("gemini", f"Quiz {quiz_plan.id} generated by Gemini ({model or settings.quiz_model})")
            return pack
        except Exception as exc:
            record_generation_source("mock", f"Quiz {quiz_plan.id} fell back to mock: {exc}")

    record_generation_source("mock", f"Quiz {quiz_plan.id} generated by mock")
    return generate_mock_quiz_pack(plan, quiz_plan, document_packs)


def generate_mock_quiz_pack(
    plan: CoursePlan,
    quiz_plan: PlanQuizPack,
    document_packs: list[SokqaDocumentPack],
) -> SokqaQuizPack:
    snippets = _source_snippets(document_packs)
    questions: list[SokqaQuestion] = []
    for index in range(1, quiz_plan.questionCount + 1):
        source = snippets[(index - 1) % len(snippets)]
        answer_index = (index - 1) % 4
        correct = f"{plan.title}の内容を、用語と使われ方を結びつけて理解する"
        distractors = [
            "本文にない細かな例外だけを暗記する",
            "用語名だけを覚えて意味を確認しない",
            "一度だけ読んで復習を省略する",
        ]
        choices = distractors.copy()
        choices.insert(answer_index, correct)
        questions.append(
            SokqaQuestion(
                id=f"q-{index}",
                question=f"{quiz_plan.title} {index}: 次の説明に基づく理解として最も適切なものはどれですか？",
                choices=choices[:4],
                answerIndex=answer_index,
                explanation=f"この問題は生成済みドキュメントの内容に基づいています。根拠: {source[:120]}",
                tags=[quiz_plan.purpose, plan.id],
            )
        )

    return SokqaQuizPack(
        id=f"{plan.id}_{quiz_plan.id}",
        title=quiz_plan.title,
        description=f"{plan.title}のドキュメント本文に基づく{quiz_plan.title}です。",
        language=plan.language,
        author=plan.author,
        globalTags=[plan.id, quiz_plan.purpose],
        questions=questions,
    )


def normalize_quiz_content(content: dict, plan: CoursePlan, quiz_plan: PlanQuizPack) -> dict:
    normalized = dict(content)
    normalized.setdefault("id", f"{plan.id}_{quiz_plan.id}")
    normalized.setdefault("type", "quiz")
    normalized.setdefault("schemaVersion", 1)
    normalized.setdefault("title", quiz_plan.title)
    normalized.setdefault("description", f"{plan.title}のドキュメント本文に基づく{quiz_plan.title}です。")
    normalized.setdefault("language", plan.language)
    normalized.setdefault("author", plan.author)
    normalized.setdefault("globalTags", [plan.id, quiz_plan.purpose])

    fixed_questions = []
    for index, item in enumerate(normalized.get("questions") or [], start=1):
        if not isinstance(item, dict):
            continue
        fixed = dict(item)
        fixed["id"] = fixed.get("id") or f"q-{index}"
        fixed["question"] = fixed.get("question") or fixed.get("prompt") or f"{quiz_plan.title} {index}"
        fixed["choices"] = [normalize_choice(choice) for choice in list(fixed.get("choices") or [])]
        while len(fixed["choices"]) < 4:
            fixed["choices"].append(f"補足選択肢{len(fixed['choices']) + 1}")
        fixed["choices"] = fixed["choices"][:4]
        try:
            answer_index = int(fixed.get("answerIndex", 0))
        except (TypeError, ValueError):
            answer_index = 0
        fixed["answerIndex"] = min(3, max(0, answer_index))
        fixed["explanation"] = fixed.get("explanation") or "生成済みドキュメント本文に基づく解説です。"
        fixed.pop("tts", None)
        fixed.pop("tags", None)
        fixed_questions.append(fixed)

    normalized["questions"] = fixed_questions
    return normalized


def normalize_choice(choice) -> str:
    if isinstance(choice, str):
        return choice
    if isinstance(choice, dict):
        return str(choice.get("text") or choice.get("label") or choice.get("choice") or choice.get("value") or "")
    return str(choice)

