import random

from app.schemas.sokqa import CoursePlan, PlanQuizPack, SokqaDocumentPack, SokqaQuestion, SokqaQuizPack
from app.config import get_settings
from app.services.gemini_client import GeminiClient
from app.services.generation_status import record_generation_source
from app.services.llm_json import LlmJsonParseContext
from app.services.pack_ids import quiz_pack_id
from app.services.prompts import quiz_generation_prompt
from app.services.tagging import quiz_global_tags


def _source_snippets(document_packs: list[SokqaDocumentPack], plan: CoursePlan | None = None) -> list[str]:
    snippets: list[str] = []
    for pack in document_packs:
        for item in pack.documents:
            snippets.append(item.text)
    if not snippets and plan and plan.sourceText:
        snippets.append(plan.sourceText)
    return snippets or ["学習内容を確認します。"]


def _language_base(language: str | None) -> str:
    return (language or "ja").split("-")[0].lower()


def quiz_description(plan: CoursePlan, quiz_plan: PlanQuizPack) -> str:
    base = _language_base(plan.language)
    if base == "ja":
        return f"{plan.title}のドキュメント本文に基づく{quiz_plan.title}です。"
    if base == "id":
        return f"Kuis {quiz_plan.title} berdasarkan materi dokumen {plan.title}."
    if base == "ko":
        return f"{plan.title} 문서 내용을 바탕으로 한 {quiz_plan.title}입니다."
    if base == "zh":
        return f"基于 {plan.title} 文档内容的 {quiz_plan.title}。"
    if base == "es":
        return f"Cuestionario {quiz_plan.title} basado en los documentos de {plan.title}."
    return f"{quiz_plan.title} based on the document content for {plan.title}."


def generate_quiz_pack(
    plan: CoursePlan,
    quiz_plan: PlanQuizPack,
    document_packs: list[SokqaDocumentPack],
    model: str | None = None,
) -> SokqaQuizPack:
    if get_settings().gemini_provider == "gemini":
        try:
            settings = get_settings()
            content = GeminiClient().generate_json(
                quiz_generation_prompt(plan, quiz_plan, document_packs),
                model=model or settings.quiz_model,
                parse_context=LlmJsonParseContext(
                    generation_unit="quiz",
                    model=model or settings.quiz_model,
                    theme=plan.title,
                    quiz_id=quiz_plan.id,
                    title=quiz_plan.title,
                    source_text=plan.sourceText,
                    additional_instructions=plan.customInstructions,
                    tts_reading_mode=plan.ttsReadingMode,
                    language=plan.language,
                    difficulty=plan.difficulty,
                    scale=plan.scale,
                ),
            )
            content = normalize_quiz_content(content, plan, quiz_plan)
            pack = SokqaQuizPack.model_validate(content)
            record_generation_source("gemini", f"Quiz {quiz_plan.id} generated by Gemini ({model or settings.quiz_model})")
            return pack
        except Exception as exc:
            record_generation_source("gemini", f"Quiz {quiz_plan.id} generation failed: {exc}")
            raise RuntimeError(
                f"クイズ生成に失敗しました（{quiz_plan.id}: {quiz_plan.title}）。"
                "失敗時テンプレートの混入を防ぐため、この生成結果は保存していません。"
                f"詳細: {exc}"
            ) from exc

    record_generation_source("mock", f"Quiz {quiz_plan.id} generated by mock")
    return generate_mock_quiz_pack(plan, quiz_plan, document_packs)


def generate_mock_quiz_pack(
    plan: CoursePlan,
    quiz_plan: PlanQuizPack,
    document_packs: list[SokqaDocumentPack],
    seed: int | str | bytes | bytearray | None = None,
) -> SokqaQuizPack:
    snippets = _source_snippets(document_packs, plan)
    questions: list[SokqaQuestion] = []
    answer_targets = _shuffled_balanced_targets(quiz_plan.questionCount, 4, _randomizer(seed))
    for index, answer_index in enumerate(answer_targets, start=1):
        source = snippets[(index - 1) % len(snippets)]
        correct = f"{plan.title}の内容を、用語と使われ方を結びつけて理解する"
        distractors = [
            "本文にない細かな例外だけを暗記する",
            "用語名だけを覚えて意味を確認しない",
            "一度だけ読んで復習を省略する",
        ]
        choices = distractors.copy()
        choices.insert(answer_index, correct)
        questions.append(
            SokqaQuestion(
                id=f"q-{index}",
                question=f"{quiz_plan.title} {index}: 次の説明に基づく理解として最も適切なものはどれですか？",
                choices=choices[:4],
                answerIndex=answer_index,
                explanation=f"この問題は生成済みドキュメントの内容に基づいています。根拠: {source[:120]}",
                tags=[quiz_plan.purpose, plan.id],
            )
        )

    return SokqaQuizPack(
        id=quiz_pack_id(plan, quiz_plan),
        title=quiz_plan.title,
        description=quiz_description(plan, quiz_plan),
        language=plan.language,
        author=plan.author,
        globalTags=quiz_global_tags(plan, quiz_plan),
        questions=questions,
    )


def normalize_quiz_content(
    content: dict,
    plan: CoursePlan,
    quiz_plan: PlanQuizPack,
    seed: int | str | bytes | bytearray | None = None,
) -> dict:
    normalized = dict(content)
    normalized["id"] = quiz_pack_id(plan, quiz_plan)
    normalized.setdefault("type", "quiz")
    normalized.setdefault("schemaVersion", 1)
    normalized.setdefault("title", quiz_plan.title)
    normalized.setdefault("description", quiz_description(plan, quiz_plan))
    normalized.setdefault("language", plan.language)
    normalized.setdefault("author", plan.author)
    normalized["globalTags"] = quiz_global_tags(plan, quiz_plan)

    fixed_questions = []
    for index, item in enumerate(normalized.get("questions") or [], start=1):
        if not isinstance(item, dict):
            continue
        fixed = dict(item)
        fixed["id"] = fixed.get("id") or f"q-{index}"
        fixed["question"] = fixed.get("question") or fixed.get("prompt") or f"{quiz_plan.title} {index}"
        fixed["choices"] = [normalize_choice(choice) for choice in list(fixed.get("choices") or [])]
        while len(fixed["choices"]) < 4:
            fixed["choices"].append(f"補足選択肢{len(fixed['choices']) + 1}")
        fixed["choices"] = fixed["choices"][:4]
        fixed["answerIndex"] = normalize_answer_index(fixed.get("answerIndex", 0))
        fixed["explanation"] = fixed.get("explanation") or "生成済みドキュメント本文に基づく解説です。"
        fixed.pop("tts", None)
        fixed.pop("tags", None)
        fixed_questions.append(fixed)

    if plan.answerPositionMode == "balanced":
        _balance_answer_positions(fixed_questions, seed=seed)
    normalized["questions"] = fixed_questions
    return normalized


def _randomizer(seed: int | str | bytes | bytearray | None = None):
    return random.Random(seed) if seed is not None else random.SystemRandom()


def _is_regular_cycle(targets: list[int], option_count: int) -> bool:
    if option_count <= 1 or len(targets) < option_count * 2:
        return False
    return any(
        all(target == (index + offset) % option_count for index, target in enumerate(targets))
        for offset in range(option_count)
    )


def _shuffled_balanced_targets(count: int, option_count: int, rng) -> list[int]:
    if count <= 0 or option_count <= 0:
        return []

    targets = [position for _ in range(count // option_count) for position in range(option_count)]
    targets.extend(range(count % option_count))
    if len(targets) <= 1:
        return targets

    best = targets.copy()
    fewest_runs = len(targets)
    for _ in range(100):
        candidate = targets.copy()
        rng.shuffle(candidate)
        run_count = sum(
            1
            for index in range(2, len(candidate))
            if candidate[index] == candidate[index - 1] == candidate[index - 2]
        )
        if run_count < fewest_runs:
            best = candidate
            fewest_runs = run_count
        if run_count == 0 and not _is_regular_cycle(candidate, option_count):
            return candidate
    return best


def _balance_answer_positions(
    questions: list[dict],
    seed: int | str | bytes | bytearray | None = None,
) -> None:
    rng = _randomizer(seed)
    grouped_indexes: dict[int, list[int]] = {}
    for index, question in enumerate(questions):
        choices = question.get("choices")
        if not isinstance(choices, list) or not choices:
            continue
        grouped_indexes.setdefault(min(4, len(choices)), []).append(index)

    targets_by_index: dict[int, int] = {}
    for option_count, indexes in grouped_indexes.items():
        for question_index, target in zip(indexes, _shuffled_balanced_targets(len(indexes), option_count, rng)):
            targets_by_index[question_index] = target

    for index, question in enumerate(questions):
        choices = question.get("choices")
        if not isinstance(choices, list) or not choices or index not in targets_by_index:
            continue
        current = min(len(choices) - 1, normalize_answer_index(question.get("answerIndex", 0)))
        target = targets_by_index[index]
        if current == target:
            question["answerIndex"] = current
            continue
        choices[current], choices[target] = choices[target], choices[current]
        question["answerIndex"] = target


def normalize_choice(choice) -> str:
    if isinstance(choice, str):
        return choice
    if isinstance(choice, dict):
        return str(choice.get("text") or choice.get("label") or choice.get("choice") or choice.get("value") or "")
    return str(choice)


def normalize_answer_index(value) -> int:
    try:
        answer_index = int(value)
    except (TypeError, ValueError):
        answer_index = 0
    return min(3, max(0, answer_index))
