import logging
import re
import random
import time

from app.schemas.sokqa import CoursePlan, PlanQuizPack, SokqaDocumentPack, SokqaQuestion, SokqaQuizPack
from app.config import get_settings
from app.services.document_generator import sanitize_learner_facing_text
from app.services.gemini_client import GeminiClient
from app.services.generation_status import record_generation_source
from app.services.llm_json import LlmJsonParseContext, LlmJsonParseError
from app.services.language_detection import choice_set_language_state
from app.services.pack_ids import quiz_pack_id
from app.services.prompts import quiz_generation_prompt, quiz_pack_violation_repair_prompt, quiz_shortage_repair_prompt
from app.services.tagging import quiz_global_tags


logger = logging.getLogger(__name__)


def _source_snippets(document_packs: list[SokqaDocumentPack], plan: CoursePlan | None = None) -> list[str]:
    snippets: list[str] = []
    for pack in document_packs:
        for item in pack.documents:
            snippets.append(item.text)
    if not snippets and plan and plan.sourceText:
        snippets.append(plan.sourceText)
    return snippets or ["学習内容を確認します。"]


def _language_base(language: str | None) -> str:
    return (language or "ja").split("-")[0].lower()


def quiz_description(plan: CoursePlan, quiz_plan: PlanQuizPack) -> str:
    base = _language_base(plan.language)
    if base == "ja":
        return f"{plan.title}のドキュメント本文に基づく{quiz_plan.title}です。"
    if base == "id":
        return f"Kuis {quiz_plan.title} berdasarkan materi dokumen {plan.title}."
    if base == "ko":
        return f"{plan.title} 문서 내용을 바탕으로 한 {quiz_plan.title}입니다."
    if base == "zh":
        return f"基于 {plan.title} 文档内容的 {quiz_plan.title}。"
    if base == "es":
        return f"Cuestionario {quiz_plan.title} basado en los documentos de {plan.title}."
    return f"{quiz_plan.title} based on the document content for {plan.title}."


def generate_quiz_pack(
    plan: CoursePlan,
    quiz_plan: PlanQuizPack,
    document_packs: list[SokqaDocumentPack],
    model: str | None = None,
) -> SokqaQuizPack:
    if get_settings().gemini_provider == "gemini":
        try:
            settings = get_settings()
            prompt = quiz_generation_prompt(plan, quiz_plan, document_packs)
            content = _generate_quiz_json_with_retry(
                prompt,
                quiz_plan=quiz_plan,
                model=model or settings.quiz_model,
                plan=plan,
            )
            content = normalize_quiz_content(content, plan, quiz_plan)
            pack = SokqaQuizPack.model_validate(content)

            # 問題②: choiceLanguageMode="pack" なのに一部問題で選択肢が学習言語になった場合、
            # 違反問題のみを厳格プロンプトで再生成して pack言語へ是正する。
            if quiz_plan.choiceLanguageMode == "pack" and plan.learningLanguage:
                content = _repair_pack_language_violations(
                    content, plan, quiz_plan, model=model or settings.quiz_model
                )
                pack = SokqaQuizPack.model_validate(content)

            # 問題①: questionCount に満たない場合、不足分のみを補完生成する。
            expected_count = quiz_plan.questionCount
            actual_count = len(content.get("questions") or [])
            if expected_count and actual_count < expected_count:
                content = _supplement_quiz_questions(
                    content, plan, quiz_plan, expected_count - actual_count, model=model or settings.quiz_model
                )
                pack = SokqaQuizPack.model_validate(content)
            record_generation_source("gemini", f"Quiz {quiz_plan.id} generated by Gemini ({model or settings.quiz_model})")
            _log_generated_quiz_units(pack, model or settings.quiz_model)
            return pack
        except Exception as exc:
            record_generation_source("gemini", f"Quiz {quiz_plan.id} generation failed: {exc}")
            raise RuntimeError(
                f"クイズ生成に失敗しました（{quiz_plan.id}: {quiz_plan.title}）。"
                "失敗時テンプレートの混入を防ぐため、この生成結果は保存していません。"
                f"詳細: {exc}"
            ) from exc

    record_generation_source("mock", f"Quiz {quiz_plan.id} generated by mock")
    return generate_mock_quiz_pack(plan, quiz_plan, document_packs)


def _generate_quiz_json_with_retry(
    prompt: str,
    *,
    quiz_plan: PlanQuizPack,
    model: str,
    plan: CoursePlan,
    attempts: int = 3,
) -> dict:
    last_error: Exception | None = None
    delays = (0.5, 1.5)
    for attempt in range(1, attempts + 1):
        try:
            return GeminiClient().generate_json(
                prompt if attempt == 1 else prompt + "\n\nPrevious output had a JSON syntax error. Return the same requested content as valid JSON only; no Markdown or commentary.",
                model=model,
                parse_context=LlmJsonParseContext(
                    generation_unit="quiz",
                    model=model,
                    theme=plan.title,
                    quiz_id=quiz_plan.id,
                    title=quiz_plan.title,
                    source_text=plan.sourceText,
                    additional_instructions=plan.customInstructions,
                    tts_reading_mode=plan.ttsReadingMode,
                    language=plan.language,
                    difficulty=plan.difficulty,
                    scale=plan.scale,
                ),
            )
        except Exception as exc:
            last_error = exc
            parse = exc if isinstance(exc, LlmJsonParseError) else None
            line, column, position = _json_error_position(parse)
            logger.warning(
                "quiz_generation.%s file_id=%s attempt=%s max_attempts=%s exception_type=%s json_parse_line=%s json_parse_column=%s char_position=%s error=%s",
                "failed" if attempt >= attempts else "retry", quiz_plan.id, attempt, attempts, type(exc).__name__, line, column, position, repr(exc),
            )
            if attempt >= attempts:
                break
            time.sleep(delays[min(attempt - 1, len(delays) - 1)])
    raise last_error or RuntimeError(f"quiz generation failed: {quiz_plan.id}")


def _json_error_position(error: LlmJsonParseError | None) -> tuple[str, str, str]:
    if not error or not error.attempts:
        return "", "", ""
    message = error.attempts[-1].get("error", "")
    match = re.search(r"line (\d+) column (\d+) \(char (\d+)\)", message)
    return match.groups() if match else ("", "", "")


def generate_mock_quiz_pack(
    plan: CoursePlan,
    quiz_plan: PlanQuizPack,
    document_packs: list[SokqaDocumentPack],
    seed: int | str | bytes | bytearray | None = None,
) -> SokqaQuizPack:
    snippets = _source_snippets(document_packs, plan)
    questions: list[SokqaQuestion] = []
    answer_targets = _shuffled_balanced_targets(quiz_plan.questionCount, 4, _randomizer(seed))
    for index, answer_index in enumerate(answer_targets, start=1):
        source = snippets[(index - 1) % len(snippets)]
        correct = f"{plan.title}の内容を、用語と使われ方を結びつけて理解する"
        distractors = [
            "本文にない細かな例外だけを暗記する",
            "用語名だけを覚えて意味を確認しない",
            "一度だけ読んで復習を省略する",
        ]
        choices = distractors.copy()
        choices.insert(answer_index, correct)
        questions.append(
            SokqaQuestion(
                id=f"q-{index}",
                question=f"{quiz_plan.title} {index}: 次の説明に基づく理解として最も適切なものはどれですか？",
                choices=choices[:4],
                answerIndex=answer_index,
                explanation=f"この問題は生成済みドキュメントの内容に基づいています。根拠: {source[:120]}",
                tags=[quiz_plan.purpose, plan.id],
            )
        )

    return SokqaQuizPack(
        id=quiz_pack_id(plan, quiz_plan),
        title=quiz_plan.title,
        description=quiz_description(plan, quiz_plan),
        language=plan.language,
        learningLanguage=plan.learningLanguage,
        choiceLanguageMode=quiz_plan.choiceLanguageMode,
        author=plan.author,
        globalTags=quiz_global_tags(plan, quiz_plan),
        questions=questions,
    )


def normalize_quiz_content(
    content: dict,
    plan: CoursePlan,
    quiz_plan: PlanQuizPack,
    seed: int | str | bytes | bytearray | None = None,
) -> dict:
    normalized = dict(content)
    normalized["id"] = quiz_pack_id(plan, quiz_plan)
    normalized.setdefault("type", "quiz")
    normalized.setdefault("schemaVersion", 1)
    normalized.setdefault("title", quiz_plan.title)
    normalized.setdefault("description", quiz_description(plan, quiz_plan))
    normalized.setdefault("language", plan.language)
    normalized["learningLanguage"] = plan.learningLanguage
    normalized["choiceLanguageMode"] = quiz_plan.choiceLanguageMode
    normalized.setdefault("author", plan.author)
    normalized["globalTags"] = quiz_global_tags(plan, quiz_plan)

    fixed_questions = []
    for index, item in enumerate(normalized.get("questions") or [], start=1):
        if not isinstance(item, dict):
            continue
        fixed = dict(item)
        fixed["id"] = fixed.get("id") or f"q-{index}"
        fixed["question"] = sanitize_learner_facing_text(
            str(fixed.get("question") or fixed.get("prompt") or f"{quiz_plan.title} {index}")
        )
        fixed["choices"] = [
            sanitize_learner_facing_text(normalize_choice(choice))
            for choice in list(fixed.get("choices") or [])
        ]
        while len(fixed["choices"]) < 4:
            fixed["choices"].append(f"補足選択肢{len(fixed['choices']) + 1}")
        fixed["choices"] = fixed["choices"][:4]
        fixed["answerIndex"] = normalize_answer_index(fixed.get("answerIndex", 0))
        fixed["explanation"] = sanitize_learner_facing_text(
            str(fixed.get("explanation") or "生成済みドキュメント本文に基づく解説です。")
        )
        fixed.pop("tts", None)
        fixed.pop("tags", None)
        fixed_questions.append(fixed)

    if plan.answerPositionMode == "balanced":
        _balance_answer_positions(fixed_questions, seed=seed)
    normalized["questions"] = fixed_questions

    expected_count = quiz_plan.questionCount
    if expected_count and len(fixed_questions) != expected_count:
        logger.warning(
            "quiz_generator.question_count_mismatch quiz=%s expected=%s actual=%s",
            quiz_plan.id,
            expected_count,
            len(fixed_questions),
        )
    return normalized


def _pack_language_violations(content: dict, plan: CoursePlan, quiz_plan: PlanQuizPack) -> list[dict]:
    """choiceLanguageMode="pack" なのに選択肢が学習言語になっている問題を検知する。"""
    if quiz_plan.choiceLanguageMode != "pack" or not plan.learningLanguage:
        return []
    violations: list[dict] = []
    for question in content.get("questions") or []:
        if not isinstance(question, dict):
            continue
        choices = [str(choice) for choice in question.get("choices") or []]
        if not choices:
            continue
        state = choice_set_language_state(choices, plan.language, str(plan.learningLanguage))
        if state in {"learning", "mixed"}:
            violations.append({"id": question.get("id"), "question": question.get("question", "")})
    return violations


def _repair_pack_language_violations(
    content: dict,
    plan: CoursePlan,
    quiz_plan: PlanQuizPack,
    *,
    model: str | None = None,
) -> dict:
    """packモード違反の問題のみを、厳格プロンプトで再生成して pack言語へ是正する。

    検知された違反問題の id をキーに、再生成結果で choices を置換する。
    再生成に失敗した場合は元の content をそのまま返す（部分適用しない）。
    """
    violations = _pack_language_violations(content, plan, quiz_plan)
    if not violations:
        return content

    violation_ids = {violation["id"] for violation in violations}
    logger.warning(
        "quiz_generator.pack_language_violations.detected quiz=%s count=%s question_ids=%s",
        quiz_plan.id,
        len(violations),
        sorted(str(item) for item in violation_ids),
    )
    try:
        logger.info(
            "quiz_generator.pack_language_violations.repair_started quiz=%s count=%s question_ids=%s",
            quiz_plan.id, len(violations), sorted(str(item) for item in violation_ids),
        )
        prompt = quiz_pack_violation_repair_prompt(plan, quiz_plan, violations)
        repaired = GeminiClient().generate_json(
            prompt,
            model=model,
            parse_context=LlmJsonParseContext(
                generation_unit="quiz",
                model=model,
                theme=plan.title,
                quiz_id=quiz_plan.id,
                title=quiz_plan.title,
                source_text=plan.sourceText,
                additional_instructions=plan.customInstructions,
                tts_reading_mode=plan.ttsReadingMode,
                language=plan.language,
                difficulty=plan.difficulty,
                scale=plan.scale,
            ),
        )
    except Exception as exc:
        logger.warning(
            "quiz_generator.pack_violation_repair_failed quiz=%s error=%s",
            quiz_plan.id,
            repr(exc),
        )
        logger.warning("quiz_generator.pack_language_violations.remaining quiz=%s count=%s", quiz_plan.id, len(violations))
        return content

    repaired_by_id = {
        item.get("id"): item
        for item in repaired.get("questions") or []
        if isinstance(item, dict) and item.get("id") in violation_ids
    }
    if not repaired_by_id:
        logger.warning("quiz_generator.pack_language_violations.remaining quiz=%s count=%s", quiz_plan.id, len(violations))
        return content

    fixed_questions = []
    for question in content.get("questions") or []:
        if not isinstance(question, dict):
            fixed_questions.append(question)
            continue
        if question.get("id") in repaired_by_id:
            fixed = dict(question)
            repaired_item = repaired_by_id[question["id"]]
            fixed["choices"] = [
                sanitize_learner_facing_text(normalize_choice(choice))
                for choice in list(repaired_item.get("choices") or [])
            ]
            while len(fixed["choices"]) < 4:
                fixed["choices"].append(f"support choice {len(fixed['choices']) + 1}")
            fixed["choices"] = fixed["choices"][:4]
            fixed["answerIndex"] = normalize_answer_index(repaired_item.get("answerIndex", fixed.get("answerIndex", 0)))
            fixed_questions.append(fixed)
        else:
            fixed_questions.append(question)
    content = dict(content)
    content["questions"] = fixed_questions
    remaining = _pack_language_violations(content, plan, quiz_plan)
    logger.info(
        "quiz_generator.pack_language_violations.repair_completed quiz=%s repaired_count=%s remaining_count=%s",
        quiz_plan.id, len(violations) - len(remaining), len(remaining),
    )
    if remaining:
        logger.warning("quiz_generator.pack_language_violations.remaining quiz=%s count=%s", quiz_plan.id, len(remaining))
    return content


def _supplement_quiz_questions(
    content: dict,
    plan: CoursePlan,
    quiz_plan: PlanQuizPack,
    missing_count: int,
    *,
    model: str | None = None,
) -> dict:
    """問題①の案A: questionCount に満たない場合、不足分のみを補完生成して結合する。

    既存の全問題を補完プロンプトに渡し、重複・id衝突を防ぐ。
    補完生成に失敗した場合は元の content をそのまま返す（不完全でも崩さない）。
    """
    existing_questions = [q for q in content.get("questions") or [] if isinstance(q, dict)]
    if missing_count <= 0 or not existing_questions:
        return content

    logger.warning(
        "quiz_generator.supplement_questions quiz=%s missing=%s",
        quiz_plan.id,
        missing_count,
    )
    try:
        prompt = quiz_shortage_repair_prompt(plan, quiz_plan, existing_questions, missing_count)
        supplemented = GeminiClient().generate_json(
            prompt,
            model=model,
            parse_context=LlmJsonParseContext(
                generation_unit="quiz",
                model=model,
                theme=plan.title,
                quiz_id=quiz_plan.id,
                title=quiz_plan.title,
                source_text=plan.sourceText,
                additional_instructions=plan.customInstructions,
                tts_reading_mode=plan.ttsReadingMode,
                language=plan.language,
                difficulty=plan.difficulty,
                scale=plan.scale,
            ),
        )
    except Exception as exc:
        logger.warning(
            "quiz_generator.supplement_failed quiz=%s error=%s",
            quiz_plan.id,
            repr(exc),
        )
        return content

    new_questions = [
        item for item in supplemented.get("questions") or [] if isinstance(item, dict)
    ]
    if not new_questions:
        return content

    # 新規問題を既存の choices 等と同じ正規化パイプへ通し、既存と結合後に全体で normalize する。
    merged = dict(content)
    merged["questions"] = existing_questions + new_questions
    merged = normalize_quiz_content(merged, plan, quiz_plan)
    return merged


def _randomizer(seed: int | str | bytes | bytearray | None = None):
    return random.Random(seed) if seed is not None else random.SystemRandom()


def _is_regular_cycle(targets: list[int], option_count: int) -> bool:
    if option_count <= 1 or len(targets) < option_count * 2:
        return False
    return any(
        all(target == (index + offset) % option_count for index, target in enumerate(targets))
        for offset in range(option_count)
    )


def _shuffled_balanced_targets(count: int, option_count: int, rng) -> list[int]:
    if count <= 0 or option_count <= 0:
        return []

    targets = [position for _ in range(count // option_count) for position in range(option_count)]
    targets.extend(range(count % option_count))
    if len(targets) <= 1:
        return targets

    best = targets.copy()
    fewest_runs = len(targets)
    for _ in range(100):
        candidate = targets.copy()
        rng.shuffle(candidate)
        run_count = sum(
            1
            for index in range(2, len(candidate))
            if candidate[index] == candidate[index - 1] == candidate[index - 2]
        )
        if run_count < fewest_runs:
            best = candidate
            fewest_runs = run_count
        if run_count == 0 and not _is_regular_cycle(candidate, option_count):
            return candidate
    return best


def _balance_answer_positions(
    questions: list[dict],
    seed: int | str | bytes | bytearray | None = None,
) -> None:
    rng = _randomizer(seed)
    grouped_indexes: dict[int, list[int]] = {}
    for index, question in enumerate(questions):
        choices = question.get("choices")
        if not isinstance(choices, list) or not choices:
            continue
        grouped_indexes.setdefault(min(4, len(choices)), []).append(index)

    targets_by_index: dict[int, int] = {}
    for option_count, indexes in grouped_indexes.items():
        for question_index, target in zip(indexes, _shuffled_balanced_targets(len(indexes), option_count, rng)):
            targets_by_index[question_index] = target

    for index, question in enumerate(questions):
        choices = question.get("choices")
        if not isinstance(choices, list) or not choices or index not in targets_by_index:
            continue
        current = min(len(choices) - 1, normalize_answer_index(question.get("answerIndex", 0)))
        target = targets_by_index[index]
        if current == target:
            question["answerIndex"] = current
            continue
        choices[current], choices[target] = choices[target], choices[current]
        question["answerIndex"] = target


def normalize_choice(choice) -> str:
    if isinstance(choice, str):
        return choice
    if isinstance(choice, dict):
        return str(choice.get("text") or choice.get("label") or choice.get("choice") or choice.get("value") or "")
    return str(choice)


def normalize_answer_index(value) -> int:
    try:
        answer_index = int(value)
    except (TypeError, ValueError):
        answer_index = 0
    return min(3, max(0, answer_index))


# 生成直後の中間物を追跡可能にするため、ユニット単位で fingerprint を記録する。
# 固定サンプル名・全文ダンプは避け、破損検出に必要な範囲(id・文字数・先頭 fingerprint)に絞る。
_LOG_FINGERPRINT_LENGTH = 40


def _quiz_field_fingerprint(value: str) -> str:
    return (value or "")[:_LOG_FINGERPRINT_LENGTH].replace("\n", " ")


def _log_generated_quiz_units(pack: SokqaQuizPack, model: str) -> None:
    for question in pack.questions:
        logger.info(
            "generation.quiz_produced file=%s unit_id=%s model=%s question_chars=%s question_fingerprint=%r explanation_chars=%s explanation_fingerprint=%r",
            pack.id,
            question.id,
            model,
            len(question.question or ""),
            _quiz_field_fingerprint(question.question),
            len(question.explanation or ""),
            _quiz_field_fingerprint(question.explanation),
        )
